import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
         
          <SignedOut>
            <div className="flex justify-center items-center h-screen bg-gray-900 text-white">
              <SignInButton>
                <button className="bg-yellow-400 px-6 py-3 rounded hover:bg-yellow-300">
                  Sign In to Continue
                </button>
              </SignInButton>
            </div>
          </SignedOut>

          
          <SignedIn>
            <header className="flex justify-between items-center px-6 py-4 bg-gray-800 text-white">
              <h1 className="text-2xl font-bold">CodersHub</h1>
              <UserButton />
            </header>

           
            <main>{children}</main>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}


